source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, UserDetailView, UserPersonalInfoChangeView, UserPasswordChangeView, UserIndexView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='update'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UserIndexView.as_view(), name='user_index')
]

source/api_v2/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from api_v2 import views

routers = routers.DefaultRouter()
routers.register(r'projects', views.ProjectViewSet)
routers.register(r'tasks', views.TaskViewSet)

app_name = 'api_v2'

urlpatterns = [
    path('', include(routers.urls)),
    path('login/', obtain_auth_token, name='api_token_auth')
]

source/tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v2/', include('api_v2.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, TaskView, TaskCreateView, TaskUpdateView, TaskDeleteView,\
    StatusCreateView, TypesCreateView, StatusUpdateView, TypesUpdateView, StatusDeleteView, TypesDeleteView,\
    ProjectView, ProjectListView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete_project'),
    path('task/', IndexView.as_view(), name='index'),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('project/<int:pk>/add-task/', TaskCreateView.as_view(), name='task_add'),
    path('status/add/', StatusCreateView.as_view(), name='status_add'),
    path('types/add/', TypesCreateView.as_view(), name='types_add'),
    path('task/<int:pk>/edit/', TaskUpdateView.as_view(), name='task_update'),
    path('status/<int:pk>/edit/', StatusUpdateView.as_view(), name='status_update'),
    path('types/<int:pk>/edit/', TypesUpdateView.as_view(), name='types_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete_task'),
    path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='delete_status'),
    path('types/<int:pk>/delete/', TypesDeleteView.as_view(), name='delete_types')
]

source/accounts/models.py
from django.db import models

from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    about_me = models.TextField(max_length=3000, null=True, blank=True, verbose_name='О себе')
    git_http = models.URLField(null=True, blank=True, verbose_name='Профиль на гитхаб')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Team(models.Model):
    user = models.ForeignKey(User, related_name='team', on_delete=models.CASCADE, verbose_name='Пользователь')
    project = models.ForeignKey('webapp.Project', related_name='team', on_delete=models.CASCADE, verbose_name='Проект')
    start_date = models.DateField(verbose_name='Дата начала работы', null=True, blank=True)
    expiration_date = models.DateField(verbose_name='Дата окончания работы', null=True, blank=True)

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    email = forms.EmailField(label='Email', required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists', code='user_email_exists')
        except User.DoesNotExist:
            return email

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean(self):
        super().clean()
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        if not(first_name or last_name):
            raise ValidationError('Нужно заполнить хотябы одно поле из first_name или last_name')
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    about_me = forms.CharField(max_length=3000, required=False, label='О себе', widget=widgets.Textarea)
    git_http = forms.URLField(label='Профиль на гитхаб', required=False)

    def clean_git_http(self):
        git_http = self.cleaned_data['git_http']
        if git_http == '' or not git_http.startswith('https://github.com/'):
            raise forms.ValidationError('ссылка не на гитхаб')
        return git_http

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit)
        self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile = self.instance.profile
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data[field])
        if not profile.avatar:
            profile.avatar = None
        if commit:
            profile.save()
        return profile

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'about_me', 'git_http']
        profile_fields = ['avatar', 'about_me', 'git_http']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import ListView, DetailView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect, reverse
from .forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from accounts.models import Profile


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('webapp:project_list')

    else:
        form = UserCreationForm()
    return render(request, 'create.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserPersonalInfoChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_info_change.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')


class UserIndexView(ListView):
    model = User
    template_name = 'accounts_list.html'
    form_class = UserChangeForm
    context_object_name = 'users_obj'

source/accounts/templates/accounts_list.html
{% extends 'base.html' %}

{% block content %}
    {% for user_obj in users_obj %}
        <div class="card m-2">
            <div class="card-header alert-dark">
                 Пользователь: {{ user_obj.username }}
            </div>

            <div class="card-body">
                <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
                <p class="card-text">Почта: {{ user_obj.email }}</p>
                {% if user.pk == user_obj.pk %}
                    <div class="form-row align-items-center">
                        <div class="col-auto my-1">
                            <form><a class="btn btn-primary" href="{% url 'accounts:update' user_obj.pk %}">Редактировать</a></form>
                        </div>
                        <div class="col-auto my-1">
                            <form><a class="btn btn-primary" href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></form>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    {% endfor %}
{% endblock %}

source/accounts/templates/create.html
{% extends 'base.html' %}

{% block content %}
        <div class="card m-2">
            <div class="card-header">
                Регистрация
            </div>

            <div class="card-body">
                <form method="POST" action="">
                    {% include 'partial/task_form.html' with button_text="Зарегистрироваться" %}
                </form>

            </div>
        </div>
{% endblock %}

source/accounts/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class = "container p-2">
    <div class="card">
      <div class="card-header">
        Вход
      </div>
      <div class="card-body">
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {% if has_error %}
                <p class="form-error">Неверное имя пользователя или пароль.</p>
            {% endif %}
          <div class="form-group">
            <label for="username">Имя пользователя</label>
            <input type="text" class="form-control" name="username" id="username">
          </div>
          <div class="form-group">
            <label for="password">Пароль</label>
            <input type="password" class="form-control" name="password" id="password">
          </div>
          <button type="submit" class="btn btn-primary">Войти</button>
          <a class="btn btn-primary" href="{% url 'webapp:project_list' %}" role="button">Назад</a>
        </form>
      </div>
    </div>

</div>

<script src="https://kit.fontawesome.com/4bd90500c4.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% csrf_token %}

{% block title %}Пользователь{% endblock %}

{% block dropdown %}
    {% if user.pk == user_obj.pk %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:update' user_obj.pk %}">Редактировать</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
        <div class="card m-2">
            <div class="card-header alert-dark">
                Личный кабинет
            </div>
            <div class="card-body">
              <div class="row no-gutters">
                <div class="col-md-4 " style="max-width: 400px;">
                    {% if user_obj.profile.avatar %}
                        <img src="{{ user_obj.profile.avatar.url }}" class="card-img" alt="user picture">
                    {% else %}
                        <img src="{% static 'base_avatar.jpg' %}" class="card-img" alt="base picture">
                    {% endif %}
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <p class="card-text">Имя пользователя: {{ user_obj.username }}</p>
                    <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                    <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
                    <p class="card-text">Почта: {{ user_obj.email }}</p>
                    <p class="card-text">О себе: {{ user_obj.profile.about_me }}</p>
                    <p class="card-text">Профиль на гитхабе: {{ user_obj.profile.git_http }}</p>
                  </div>
                </div>
              </div>
            </div>
        </div>
{% endblock %}

source/accounts/templates/user_info_change.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block dropdown %}
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:detail' user_obj.pk %}">Назад</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:password_change' user_obj.pk %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
        <div class="card m-2">
            <div class="card-header alert-dark">
                Личный кабинет
            </div>

            <div class="card-body">
                <form action="{% url 'accounts:update' user_obj.pk %}" method="post" enctype="multipart/form-data">
                    {% include 'partial/task_form.html' with button_text="Сохранить" %}
                </form>
            </div>
        </div>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block dropdown %}
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:detail' user_obj.pk %}">Назад</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:update' user_obj.pk %}">Редактирование
        личных данных</a></li>
{% endblock %}

{% block content %}
        <div class="card m-2">
            <div class="card-header alert-dark">
                Смена пароля
            </div>

            <div class="card-body">
                <form action="{% url 'accounts:password_change' user_obj.pk %}" method="post">
                    {% include 'partial/task_form.html' with button_text="Сохранить" %}
                </form>
            </div>
        </div>
{% endblock %}