source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_view, UserDetailView, UserPersonalInfoChangeView, UserPasswordChangeView, UserIndexView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='update'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('users/', UserIndexView.as_view(), name='user_index')
]

source/api_v2/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from api_v2 import views

routers = routers.DefaultRouter()
routers.register(r'projects', views.ProjectViewSet)
routers.register(r'tasks', views.TaskViewSet)

app_name = 'api_v2'

urlpatterns = [
    path('', include(routers.urls)),
    path('login/', obtain_auth_token, name='api_token_auth')
]

source/tracker/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v2/', include('api_v2.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, TaskView, TaskCreateView, TaskUpdateView, TaskDeleteView,\
    StatusCreateView, TypesCreateView, StatusUpdateView, TypesUpdateView, StatusDeleteView, TypesDeleteView,\
    ProjectView, ProjectListView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project/<int:pk>/edit/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete_project'),
    path('task/', IndexView.as_view(), name='index'),
    path('task/<int:pk>/', TaskView.as_view(), name='task_view'),
    path('project/<int:pk>/add-task/', TaskCreateView.as_view(), name='task_add'),
    path('status/add/', StatusCreateView.as_view(), name='status_add'),
    path('types/add/', TypesCreateView.as_view(), name='types_add'),
    path('task/<int:pk>/edit/', TaskUpdateView.as_view(), name='task_update'),
    path('status/<int:pk>/edit/', StatusUpdateView.as_view(), name='status_update'),
    path('types/<int:pk>/edit/', TypesUpdateView.as_view(), name='types_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='delete_task'),
    path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='delete_status'),
    path('types/<int:pk>/delete/', TypesDeleteView.as_view(), name='delete_types')
]

source/webapp/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название проекта')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание проекта')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.name


class Task(models.Model):
    project = models.ForeignKey('webapp.Project', related_name='task', on_delete=models.CASCADE,
                                null=True, blank=False, verbose_name='Проект')
    summary = models.CharField(max_length=200, verbose_name='Краткое описание')
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Полное описание')
    status = models.ForeignKey('webapp.Status', related_name='tasks', on_delete=models.PROTECT, verbose_name='Статус')
    types = models.ForeignKey('webapp.Types', related_name='tasks', on_delete=models.PROTECT, verbose_name='Тип')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')

    def __str__(self):
        return self.summary


class Status(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')

    def __str__(self):
        return self.name


class Types(models.Model):
    name = models.CharField(max_length=20, verbose_name='Название')

    def __str__(self):
        return self.name

source/webapp/forms.py
from django import forms
from webapp.models import Task, Types, Status, Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['created_at', 'updated_at']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['created_at', 'project']


class TypesForm(forms.ModelForm):
    class Meta:
        model = Types
        fields = ['name']


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False,label='Найти')

source/webapp/views/base_view.py
from django.views.generic import ListView
from django.utils.http import urlencode

from webapp.forms import SimpleSearchForm


class SearchView(ListView):
    from_search = None

    def get_query(self):
        return self.search_value

    def get(self, request, *args,**kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args,**kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list,**kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(self.get_query())
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

source/webapp/views/project_view.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q

from webapp.forms import ProjectForm, SimpleSearchForm
from webapp.models import Project

from webapp.views.base_view import SearchView


class ProjectListView(SearchView):
    template_name = 'project_list.html'
    context_object_name = 'projects'
    model = Project
    ordering = ['created_at']
    paginate_by = 5
    paginate_orphans = 1
    from_search = SimpleSearchForm

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        project = Project.objects.filter(team__user=self.request.user, team__expiration_date=None)
        context['users_project'] = project
        return context

    def get_query(self):
        val = super().get_query()
        query = Q(name__icontains=val)
        return query


class ProjectView(DetailView):
    template_name = 'project_view.html'
    model = Project
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.object
        tasks = project.task.order_by('-created_at')
        context['tasks'] = tasks
        return context


class ProjectCreateView(CreateView):
    template_name = 'create/create_project.html'
    model = Project
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectUpdateView(UserPassesTestMixin, UpdateView):
    model = Project
    template_name = 'update/update_project.html'
    form_class = ProjectForm
    context_object_name = 'project'

    def test_func(self):
        self.object = Project.objects.get(pk=self.kwargs['pk'])
        projects = Project.objects.filter(team__user=self.request.user)
        return self.object in projects

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'delete/delete_project.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:project_list')

    def test_func(self):
        self.object = Project.objects.get(pk=self.kwargs['pk'])
        projects = Project.objects.filter(team__user=self.request.user)
        return self.object in projects

source/webapp/views/status_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView


from webapp.forms import StatusForm
from webapp.models import Status


class StatusCreateView(LoginRequiredMixin, CreateView):
    template_name = 'create/create_status.html'
    model = Status
    form_class = StatusForm
    success_url = '/'


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'update/update_status.html'
    model = Status
    form_class = StatusForm
    context_object_name = 'status'
    success_url = '/'


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'delete/delete_ status.html'
    model = Status
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'status'

source/webapp/views/task_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q

from webapp.forms import TaskForm, SimpleSearchForm
from webapp.models import Task, Status, Types, Project

from webapp.views.base_view import SearchView


class IndexView(SearchView):
    template_name = 'index.html'
    model = Task
    context_object_name = 'Tasks'
    ordering = ['-created_at']
    paginate_by = 5
    paginate_orphans = 1
    from_search = SimpleSearchForm

    def get_query(self):
        val = super().get_query()
        query = Q(summary__icontains=val) | Q(description__icontains=val)
        return query

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['Status'] = Status.objects.all()
        context['Types'] = Types.objects.all()
        return context


class TaskView(DetailView):
    template_name = 'view.html'
    model = Task
    context_object_name = 'Task'


class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'create/create.html'
    form_class = TaskForm

    def form_valid(self, form):
        project_pk = self.kwargs.get('pk')
        project = get_object_or_404(Project,pk=project_pk)
        project.task.create(**form.cleaned_data)
        return redirect('webapp:project_view', pk=project_pk)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'update/update.html'
    model = Task
    form_class = TaskForm
    context_object_name = 'task'

    def get_success_url(self):
        return reverse('webapp:task_view', kwargs={'pk': self.object.pk})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'delete/delete.html'
    model = Task
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'task'

source/webapp/views/types_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView


from webapp.forms import TypesForm
from webapp.models import Types


class TypesCreateView(LoginRequiredMixin,CreateView):
    template_name = 'create/create_types.html'
    model = Types
    form_class = TypesForm
    success_url = '/'


class TypesUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'update/update_types.html'
    model = Types
    form_class = TypesForm
    context_object_name = 'types'
    success_url = '/'


class TypesDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'delete/delete_types.html'
    model = Types
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'types'

source/webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'webapp:project_list' %}">Issue Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:project_list' %}">Главная <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        {% block menu %}{% endblock %}
      </li>
      {% block dropdown %}{% endblock %}
            <li class="nav-item">
                <a class="nav-link text-info" href="{% url 'accounts:user_index' %}">Список пользователей </a>
            </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-info" href="{% url 'accounts:detail' user.pk %}">Привет, {{ user.username }}!</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:logout' %}" class="btn btn-danger" role="button"> Выход</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a href="{% url 'accounts:login' %}" class="btn btn-success" role="button"> Вход</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:create' %}" class="btn btn-outline-light ml-2" role="button"> Регистрация</a>
            </li>
        {% endif %}
    </ul>
      {% block search %}{% endblock %}
  </div>
</nav>

<div class = "container p-2">
{% block content %}{% endblock %}
</div>

<script src="https://kit.fontawesome.com/4bd90500c4.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block dropdown %}
<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Типы
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for Type in Types %}
            <div class="d-flex">
                <a class="dropdown-item " href="#">{{ Type.name }}</a>
                <div class="d-flex">
                <a class="dropdown-item " href="{% url 'webapp:types_update' Type.pk %}"><i class="fas fa-pencil-alt"></i></a>
                <a class="dropdown-item " href="{% url 'webapp:delete_types' Type.pk %}"><i class="fab fa-hotjar"></i></a>
                </div>
            </div>
          {% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'webapp:types_add' %}">Добавить тип</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Статусы
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for Stat in Status %}
            <div class="d-flex">
                <a class="dropdown-item" href="#">{{ Stat.name }}</a>
                <div class="d-flex">
                <a class="dropdown-item " href="{% url 'webapp:status_update' Stat.pk %}"><i class="fas fa-pencil-alt"></i></a>
                <a class="dropdown-item " href="{% url 'webapp:delete_status' Stat.pk %}"><i class="fab fa-hotjar"></i></a>
                </div>
            </div>
          {% endfor %}
            <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'webapp:status_add' %}">Добавить статус</a>
        </div>
      </li>
{% endblock %}

{% block search %}
    {% include 'partial/simple_search.html' %}
{% endblock %}

{% block content %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% for Task in Tasks %}
        <div class="card m-2">
            <div class="card-header">
                {{ Task.summary }} ({{ Task.created_at }})
            </div>

            <div class="card-body">
                <p class="card-text">Статус: {{ Task.status }}</p>
                <p class="card-text">Тип задачи: {{ Task.types }}</p>
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:delete_task' Task.pk %}" class="btn btn-primary">Удаление</a></form>
                    </div>
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:task_view' Task.pk %}" class="btn btn-primary">Подробнее</a></form>
                    </div>
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:task_update' Task.pk %}" class="btn btn-primary">Редаклирование</a></form>
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/project_list.html
{% extends 'base.html' %}

{% block menu %}
    <a class="nav-link" href="{% url 'webapp:index' %}">Задачи</a>
{% endblock %}

{% block dropdown %}
    <a class="nav-link" href="{% url 'webapp:project_add' %}">Дабавление</a>
{% endblock %}

{% block search %}
    {% include 'partial/simple_search.html' %}
{% endblock %}

{% block content %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% for project in projects %}
        <div class="card m-2">
            <div class="card-header">
                {{ project.name }} (Дата создание: {{ project.created_at }})
            </div>

            <div class="card-body">
                <p class="card-text">Дата обновления: {{ project.updated_at }}</p>
                <div class="form-row align-items-center">
                {% for project_user in users_project %}
                    {% if user.is_authenticated and project_user == project  %}
                        <div class="col-auto my-1">
                            <form><a href="{% url 'webapp:delete_project' project.pk %}" class="btn btn-primary">Удаление</a></form>
                        </div>
                        <div class="col-auto my-1">
                            <form><a href="{% url 'webapp:project_update' project.pk %}" class="btn btn-primary">Редаклирование</a></form>
                        </div>
                    {% endif %}
                {% endfor %}

                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:project_view' project.pk %}" class="btn btn-primary">Подробнее</a></form>
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/project_view.html
{% extends 'base.html' %}

{% block dropdown %}
    <a class="nav-link" href="{% url 'webapp:task_add' project.pk %}">Дабавление задачи</a>
{% endblock %}

{% block content %}
        <div class="card m-2">
            <div class="card-header alert-dark">
                {{ project.name }} (Дата создание: {{ project.created_at }})
            </div>

            <div class="card-body">
                <p class="card-text">Описание проекта: {{ project.description }}</p>
                <p class="card-text">Дата обновления: {{ project.updated_at }}</p>
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:delete_project' project.pk %}" class="btn btn-primary">Удаление</a></form>
                    </div>
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:project_update' project.pk %}" class="btn btn-primary">Редаклирование</a></form>
                    </div>
                </div>

            </div>
        </div>
    {% for task in tasks %}
        <div class="card m-2">
            <div class="card-header">
                {{ task.summary }} ({{ task.created_at }})
            </div>

            <div class="card-body">
                <p class="card-text">Статус: {{ task.status }}</p>
                <p class="card-text">Тип задачи: {{ task.types }}</p>
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:delete_task' task.pk %}" class="btn btn-primary">Удаление</a></form>
                    </div>
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:task_update' task.pk %}" class="btn btn-primary">Редаклирование</a></form>
                    </div>
                </div>

            </div>
        </div>
        {% empty %}
        <p>Нет задачь</p>
    {% endfor %}
{% endblock %}

source/webapp/templates/view.html
{% extends 'base.html' %}

{% block content %}
        <div class="card m-2">
            <div class="card-header">
                {{ Task.summary }} ({{ Task.created_at }})
            </div>

            <div class="card-body">
                <p class="card-text">Статус: {{ Task.status }}</p>
                <p class="card-text">Тип задачи: {{ Task.types }}</p>
                <p class="card-text">Полное описание: {{ Task.description }}</p>
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:delete_task' Task.pk %}" class="btn btn-primary">Удаление</a></form>
                    </div>
                    <div class="col-auto my-1">
                        <form><a href="{% url 'webapp:task_update' Task.pk %}" class="btn btn-primary">Редаклирование</a></form>
                    </div>
                </div>

            </div>
        </div>
{% endblock %}